galaxy_info:
  author: Nicolas CANIART
  description: Basic Debian Images to test Ansible Roles

  # If the issue tracker for your role is not on GitHub, uncomment the
  # next line and provide a value
  # issue_tracker_url:

  license: GPLv2

  min_ansible_container_version: 0.9.2

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If travis integration is cofigured, only notification for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  github_branch: master

  tags:
    - 'ansible'
    - 'testing'
